### ISSUE TITLE
Connection window does not work

### ISSUE THREAD

**Issue by LeszekSzejka** [jlattimer/CRMDeveloperExtensions#82] opened 2016-11-18 09:27 UTC
Hi,
strange situation: VS 2013 update 4. When creating a new connection "Connect" button does not work - like no action invoked. No info, no error. Connecting to 2016 IFD. Have tried adding additioanl org name to ifd addres and domain. Did not help.

This does not work at win10. 
Same configuration, same VS, same organisation but at win2012 works.
Both enviroments do have .net 4.6 installed

**Comment by jlattimer** [comment] 2016-11-20 04:37
Are you working with the last official release (1.3.3.0) or are you working with a fork of the current version that's in process for the next release?

**Comment by LeszekSzejka** [comment] 2016-11-20 08:44
Jason,
Official one. Tried 1.3.3 and one before. Both fails.

Maybe think about extensive logger for troubleshooting.

**Comment by jlattimer** [comment] 2016-11-20 20:29
Should be releasing 1.3.4.0 soon which addresses some connectivity issues - once that gets released, test again to see if the issue is resolved.

**Comment by jlattimer** [comment] 2016-12-12 15:05
New version released today - please re-check

**Comment by jlattimer** [comment] 2017-01-17 15:57
Closing - no updates

**Closed by jlattimer** 2017-01-17 15:57 UTC
Labels: Researching
