### ISSUE TITLE
Error adding a connection in Web Resource Deployer

### ISSUE THREAD

**Issue by JurgenPostelmans** [jlattimer/CRMDeveloperExtensions#60] opened 2016-06-10 10:07 UTC
Every time I try to create a connection to an On Premise Dynamics CRM 2016 I get the following error in the Web Resource Deployer. With dynamics CRM Online there is no issue.

The Build Number of the On Premise Dynamics CRM is 8.0.1.79

Error: 10/06/2016 12:04:17  Error Retrieving Connections From Config File: Missing CRMDeveloperExtensions.config file
Error: 10/06/2016 12:04:51  Error Connecting To CRM: Metadata contains a reference that cannot be resolved: 'http://springfield:5555/U2U/XRMServices/2011/Organization.svc?wsdl=wsdl0'.
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceConfiguration..ctor(Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateConfiguration[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Client.Services.OrganizationService.CreateServiceConfiguration(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.GetServiceConfiguration(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.ToOrganizationServiceProxy(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.ToOrganizationService(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.<>c__DisplayClass2.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Xrm.Client.Services.OrganizationService.InnerOrganizationService.get_Value()
   at Microsoft.Xrm.Client.Services.OrganizationService.Dispose()
   at CrmConnectionWindow.Connection.ConnectToCrm(String connectionString)

**Comment by KimBon** [comment] 2016-06-15 09:48
Hi 

I am having the same issue when connecting to CRM 2016 from VS 2015 or 2013.

Kind regards

Kim

**Comment by jlattimer** [comment] 2016-06-20 18:30
Have you looked at this blog post and rules out these items as causes?
http://help.clickdimensions.com/error-metadata-contains-a-reference-that-cannot-be-resolved-crm-2011/

Are you able to connect to the same url using the SDK plug-in registration tool?

**Comment by JurgenPostelmans** [comment] 2016-06-20 19:25
I've checked out the blog post above and that is definitely not the issue. And I can connect to the on-premise instance using the SDK plug-in registration tool.

I don't know if is related but I (and some other people) had the same issue with Early Bound Generator in XrmToolbox. 

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source : System.ServiceModel
Method : Retrieve
Date : 24/05/2016
Time : 10:28:23
Error : Metadata contains a reference that cannot be resolved: 'CRMPath/XRMServices/2011/Discovery.svc?wsdl&sdkversion=0'.
Stack Trace : at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
at Microsoft.Xrm.Sdk.Client.ServiceConfiguration1..ctor(Uri serviceUri, Boolean checkForSecondary) at

**Comment by KimBon** [comment] 2016-06-20 19:28
Thanks for your response. I have checked some things:
- I am using CRM 2016 on premise
- Tried plug-in registration tool of SDK 8.0.1 and 8.1.0 and both can connect to the organization via AD integrated security, using both: http://localhost:5555/xrmsolutiontests and http://<myhostname>:5555/xrmsolutiontests
- The configuration in deployment administrator has the correct URL, internal on http://localhost:5555/xrmsolutiontests
- CRM is running in a VM, and I am using Visual Studio and the tools on that same machine.
- The only IIS binding for the site is HTTP, port 5555.

**Comment by jlattimer** [comment] 2016-06-20 21:25
OK - I'll need to find/build a CRM server not set up for IFD that I can use to test this against. Might be a few days to get that sorted out.

**Comment by NathanSushi** [comment] 2016-07-05 06:28
The same issue can be reproduced in an On Premise CRM 2016 IFD Environment.
Same thing here; some XrmToolBox plugins have the same error. 

I'm assuming it is related to the Microsoft.Xrm.Tooling.Connector.dll and connecting to CRM through a connectionstring.

**Comment by YohannHaddou** [comment] 2016-09-02 07:43
Hi, 

I think I’ve found the solution. I had the same issue with Plugin Deployer : 
> "Metadata contains a reference that cannot be resolved". 

To know where provided this error I download project and in debugg I get this error : 
> "Error: Cannot obtain Metadata from http://localhost:8000/somesservice/mex The maximum nametable character count quota (16384) has been exceeded while reading XML data. The nametable is a data structure used to store strings encountered during XML processing - long XML documents with non-repeating element names, attribute names and attribute values may trigger this quota. This quota may be increased by changing the MaxNameTableCharCount property on the XmlDictionaryReaderQuotas object used when creating the XML reader. "

First I changed framework 4.5.0 to 4.5.2 in all projects. 

Then I update different nugets : 
-	Microsoft Dynamics CRM 2016 SDK coreassemblies 8.1.0.2 (https://www.nuget.org/packages/Microsoft.CrmSdk.CoreAssemblies/)
-	Microsoft.CrmSdk.Deployment 8.1.0.2 (https://www.nuget.org/packages/Microsoft.CrmSdk.Deployment/)
-	Microsoft.CrmSdk.Extensions 7.1.0.1 (https://www.nuget.org/packages/Microsoft.CrmSdk.Extensions/)
-	Microsoft.CrmSdk.Workflow 8.1.0.2 (https://www.nuget.org/packages/Microsoft.CrmSdk.Workflow/)
-	.CrmSdk.XrmTooling.CoreAssembly 8.0.2 (https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/)
-	Microsoft.IdentityModel.Clients.ActiveDirectory 2.18 (https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/)


After updates, I have modified the following references (with the new path) :
-	Microsoft.Xrm.Client (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.Extensions.7.1.0.1\lib\net45\Microsoft.Xrm.Client.dll)
-	Microsoft.Xrm.Client.CodeGeneration (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.Extensions.7.1.0.1\lib\net45\Microsoft.Xrm.Client.CodeGeneration.dll)
-	Microsoft.Xrm.Portal (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.Extensions.7.1.0.1\lib\net45\Microsoft.Xrm.Portal.dll)
-	Microsoft.Xrm.Portal.Files (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.Extensions.7.1.0.1\lib\net45\Microsoft.Xrm.Portal.Files.dll)
-	Microsoft.Xrm.Sdk (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.CoreAssemblies.8.1.0.2\lib\net452\Microsoft.Xrm.Sdk.dll)
-	Microsoft.Xrm.Sdk.Deployment (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.Deployment.8.1.0.2\lib\net452\Microsoft.Xrm.Sdk.Deployment.dll)
-	Microsoft.Crm.Sdk.Proxy (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.CoreAssemblies.8.1.0.2\lib\net452\Microsoft.Crm.Sdk.Proxy.dll)


I add this references :
-	Microsoft.Xrm.Tooling.Connector (…\CRMDeveloperExtensions-master\packages\Microsoft.CrmSdk.XrmTooling.CoreAssembly.8.0.2\lib\net45\Microsoft.Xrm.Tooling.Connector.dll)
-	Microsoft.IdentityModel.Clients.ActiveDirectory (…\CRMDeveloperExtensions-master\packages\Microsoft.IdentityModel.Clients.ActiveDirectory.2.18.206251556\lib\net45\Microsoft.IdentityModel.Clients.ActiveDirectory.dll)
-	Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms  (…\CRMDeveloperExtensions-master\packages\Microsoft.IdentityModel.Clients.ActiveDirectory.2.18.206251556\lib\net45\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll)

Finally you have to change in PluginDeployer, CrmConnectionWindow project, and WebResourceDeployer :
Every CrmConnection objects must be changed by CrmServiceClient and every organizationService by OrganizationServiceProxy. Like the following image : 

![capture](https://cloud.githubusercontent.com/assets/21670205/18196344/15fc8686-70f1-11e6-993b-9d878bf1eae7.PNG)
![capture 1](https://cloud.githubusercontent.com/assets/21670205/18196346/1b74c394-70f1-11e6-9e38-90d6573208da.PNG)
![capture 2](https://cloud.githubusercontent.com/assets/21670205/18196348/1dc871ea-70f1-11e6-9ba1-2d8026a5bccb.PNG)


Thanks to that I can connect in CRM by the plugin deployer and web resource deployer. To connect I choose « On-premises with provided user credentials » and « https://internalcrm.domain.com/org » to url.

I hope this post can be help you.

Yo'

**Comment by AJster** [comment] 2016-09-14 08:59
YohannHaddou,
can you please add your project?

**Comment by Targolo** [comment] 2016-09-22 09:25
Hi,

Same issue here, I hope there will be a new version soon.

@YohannHaddou 👍 : I've tried your solution, that's not so easy since the nuget packages have changed and the relations between them stop me from using the exact same version, especialy for ActiveDirectory (I had to use version 2.22)

At the end, I managed to change all the sources and references and recompiled everything, but at connection time, something requires Microsoft.IdentityModel.Clients.ActiveDirectory version 2.18 and it fails.

**Comment by ashwinravi** [comment] 2016-09-26 14:10
I have a similar issue trying to create a new connection to a CRM Online 2016 Update org - 8.1.0.512 (DB 8.1.0.452). The strange part is that it connects fine to another Online org with the same version. Any thoughts on this one?

Here's the detailed error and stack trace:

Error: 9/26/2016 7:04:55 AM  Error Connecting To CRM: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.

Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.IdentityModel.Protocols.WSTrust.IWSTrustContract.Issue(Message message)
   at Microsoft.IdentityModel.Protocols.WSTrust.WSTrustChannel.Issue(RequestSecurityToken rst, RequestSecurityTokenResponse& rstr)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Issue(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateTokenWithACSForCrm(AuthenticationCredentials authenticationCredentials, Uri appliesTo, Uri acsEndpoint)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(ClientCredentials clientCredentials)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceConfiguration.Authenticate(ClientCredentials clientCredentials)
   at Microsoft.Xrm.Client.Services.OrganizationService.CreateUserTokenResponse(CrmConnection connection, IServiceConfiguration`1 config)
   at Microsoft.Xrm.Client.Services.OrganizationService.GetUserTokenResponse(CrmConnection connection, IServiceConfiguration`1 config)
   at Microsoft.Xrm.Client.Services.OrganizationService.ToOrganizationServiceProxy(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.ToOrganizationService(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.<>c__DisplayClass2.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Xrm.Client.Services.OrganizationService.InnerOrganizationService.get_Value()
   at Microsoft.Xrm.Client.Services.OrganizationService.Dispose()
   at CrmConnectionWindow.Connection.ConnectToCrm(String connectionString)

**Comment by NathanSushi** [comment] 2016-10-16 20:03
I've managed to get it working using the tips mentioned y @YohannHaddou. I've checked in a fork, so you can go ahead and give it a try. 
Some points of attention:

1. When installing the 8.1.0.2 Version of the CRM Tooling, it automatically the Microsoft.IdentityModel.ActiveDirectory to version 2.28. This does **not** work. Therefore I had to add the 2.18 dll's (Microsoft.IdentiyModel.Activedirectory.dll and Microsoft.IdentiyModel.Activedirectory.winforms.dll) to the packages folder (copied from the CRM sdk) and add references to that version.

2. When connecting to an IFD environment it is required to pass the organization name in the url **and** the Domain name in **both** the domain name field & the username field:
![image](https://cloud.githubusercontent.com/assets/20294356/19420473/3feb222c-93ec-11e6-8a6a-f68f1f293a55.png)

Let me know if you want to try just the .visx file instead of building the entire solution.

**Comment by jlattimer** [comment] 2016-11-17 13:31
Should be addressed in the next release

**Comment by jlattimer** [comment] 2016-12-12 15:08
New version released which uses the Xrm.Tooling assembly for connection and should hopefully resolve issues. Closing down this issue since it got out of control. Raise a new issue for any new items.

**Closed by jlattimer** 2016-12-12 15:08 UTC
Labels: bug

**Comment by ashwinravi** [comment] 2016-12-12 16:40
Hi Jason, The last release I see over  here (https://github.com/jlattimer/CRMDeveloperExtensions/releases) was on Oct 10th and is v1.3.3. Was there supposed to a newer release I should see in that location?

**Comment by jlattimer** [comment] 2016-12-12 16:50
It's up now - if you've got VS set to auto-update extensions it should have come down that way as well

**Comment by ashwinravi** [comment] 2016-12-12 19:24
Ok, I've got the latest version and the good thing is that its able to connect to an organization now but as soon as it returns back and tries to refresh the Web Resource deployer with the solutions, etc., Visual Studio crashes and it doesn't seem to retain that connection I created before. Any ideas? Have you seen this happen?

**Comment by jlattimer** [comment] 2016-12-12 19:27
Please open a new issue for this with detailed repro steps

**Comment by mahdyar59** [comment] 2016-12-25 15:36
Hi Jason,
Thank u for this great tool.
I used the 1.3.3.0 without any problem with the 2016 and 2015 on-premise environments. But, after it updated to 1.3.4.0, I could not connect to any of them. Today, I unistalled and again install the 1.3.3.0 version and everything works fine. I think there is a problem in the 1.3.4 with on-premises.

**Comment by jlattimer** [comment] 2016-12-25 17:46
@mahdyar59 please try the pre release 1.3.4.1 in the releases area on the site to see if it helps
